variable "key_pair_name" {}
variable "private1_cidr_block" {}
variable "private2_cidr_block" {}
variable "public1_cidr_block" {}
variable "private1_availability_zone" {}
variable "private2_availability_zone" {}
variable "public1_availability_zone" {}
variable "vpc_cidr_block" {}
variable "password" {}
variable "instance_class" {}
